# Generated by Django 5.1.6 on 2025-06-22 18:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('student_id', models.CharField(max_length=50)),
                ('class_id', models.CharField(max_length=255)),
                ('test_num', models.IntegerField()),
                ('phy_total', models.IntegerField()),
                ('phy_attended', models.IntegerField()),
                ('phy_correct', models.IntegerField()),
                ('phy_score', models.IntegerField()),
                ('chem_total', models.IntegerField()),
                ('chem_attended', models.IntegerField()),
                ('chem_correct', models.IntegerField()),
                ('chem_score', models.IntegerField()),
                ('bot_total', models.IntegerField()),
                ('bot_attended', models.IntegerField()),
                ('bot_correct', models.IntegerField()),
                ('bot_score', models.IntegerField()),
                ('zoo_total', models.IntegerField()),
                ('zoo_attended', models.IntegerField()),
                ('zoo_correct', models.IntegerField()),
                ('zoo_score', models.IntegerField()),
                ('total_attended', models.IntegerField()),
                ('total_correct', models.IntegerField()),
                ('total_score', models.IntegerField()),
            ],
            options={
                'unique_together': {('student_id', 'class_id', 'test_num')},
            },
        ),

    ]
