# Generated by Django 5.1.6 on 2025-06-27 07:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gemini_ApiCallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('model_name', models.CharField(max_length=128)),
                ('function_name', models.CharField(max_length=128)),
                ('prompt_excerpt', models.TextField(blank=True)),
                ('prompt_token_count', models.IntegerField(default=0)),
                ('output_token_count', models.IntegerField(default=0)),
                ('total_token_count', models.IntegerField(default=0)),
                ('request_price', models.DecimalField(decimal_places=8, default=0, max_digits=16)),
                ('status', models.CharField(default='success', max_length=32)),
                ('duration_s', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('input_content', models.TextField(blank=True, null=True)),
                ('output_content', models.TextField(blank=True, null=True)),
                ('api_key', models.CharField(blank=True, max_length=128, null=True)),
                ('user_type', models.CharField(blank=True, max_length=64, null=True)),
                ('user_id', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'db_table': 'api_call_log',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Gemini_ApiKeyModelDayStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(max_length=128)),
                ('model_name', models.CharField(max_length=128)),
                ('timestamp_day', models.DateField()),
                ('requests_per_day', models.IntegerField(default=0)),
                ('tokens_per_day', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'api_key_model_day_stats',
                'ordering': ['-timestamp_day'],
                'unique_together': {('api_key', 'model_name', 'timestamp_day')},
            },
        ),
        migrations.CreateModel(
            name='Gemini_ApiKeyModelMinuteStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(max_length=128)),
                ('model_name', models.CharField(max_length=128)),
                ('timestamp_minute', models.DateTimeField()),
                ('requests_per_minute', models.IntegerField(default=0)),
                ('tokens_per_minute', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'api_key_model_minute_stats',
                'ordering': ['-timestamp_minute'],
                'unique_together': {('api_key', 'model_name', 'timestamp_minute')},
            },
        ),
        
    ]
