# Generated by Django 5.1.6 on 2025-10-27 11:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_educator_gemini_apicalllog_manager_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Educator',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('dob', models.DateField()),
                ('class_id', models.CharField(max_length=50)),
                ('institution', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('separate_biology_subjects', models.BooleanField(default=False)),
                ('csv_status', models.CharField(choices=[('pending', 'Pending'), ('started', 'Started'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Overview',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=50)),
                ('class_id', models.CharField(max_length=100)),
                ('metric_name', models.CharField(max_length=100)),
                ('metric_value', models.TextField()),
            ],
            options={
                'unique_together': {('user_id', 'class_id', 'metric_name')},
            },
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=50)),
                ('class_id', models.CharField(max_length=100)),
                ('subject', models.TextField()),
                ('metric_name', models.CharField(max_length=200)),
                ('metric_value', models.TextField()),
            ],
            options={
                'unique_together': {('user_id', 'class_id', 'subject', 'metric_name')},
            },
        ),
        migrations.CreateModel(
            name='QuestionAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_id', models.CharField(max_length=50)),
                ('test_num', models.IntegerField()),
                ('chapter', models.TextField()),
                ('topic', models.TextField()),
                ('subtopic', models.TextField()),
                ('subject', models.TextField()),
                ('typeOfquestion', models.TextField()),
                ('question_number', models.IntegerField()),
                ('question_text', models.TextField()),
                ('option_1', models.TextField()),
                ('option_2', models.TextField()),
                ('option_3', models.TextField()),
                ('option_4', models.TextField()),
                ('im_desp', models.TextField(blank=True, null=True)),
                ('correct_answer', models.TextField()),
                ('option_1_feedback', models.TextField()),
                ('option_2_feedback', models.TextField()),
                ('option_3_feedback', models.TextField()),
                ('option_4_feedback', models.TextField()),
                ('option_1_type', models.TextField(blank=True, null=True)),
                ('option_2_type', models.TextField(blank=True, null=True)),
                ('option_3_type', models.TextField(blank=True, null=True)),
                ('option_4_type', models.TextField(blank=True, null=True)),
                ('option_1_misconception', models.TextField(blank=True, null=True)),
                ('option_2_misconception', models.TextField(blank=True, null=True)),
                ('option_3_misconception', models.TextField(blank=True, null=True)),
                ('option_4_misconception', models.TextField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('class_id', 'test_num', 'question_number')},
            },
        ),
        migrations.CreateModel(
            name='QuestionPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_id', models.CharField(max_length=50)),
                ('test_num', models.IntegerField()),
                ('question_number', models.IntegerField()),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('question_text', models.TextField()),
                ('option_1', models.TextField()),
                ('option_2', models.TextField()),
                ('option_3', models.TextField()),
                ('option_4', models.TextField()),
                ('im_desp', models.TextField(blank=True, null=True)),
                ('correct_answer', models.TextField()),
            ],
            options={
                'unique_together': {('class_id', 'test_num', 'question_number', 'subject')},
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('student_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('class_id', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=255)),
                ('neo4j_db', models.CharField(max_length=100)),
                ('independant', models.BooleanField(default=False)),
            ],
            options={
                'unique_together': {('student_id', 'class_id')},
            },
        ),
        migrations.CreateModel(
            name='StudentResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=50)),
                ('class_id', models.CharField(max_length=50)),
                ('test_num', models.IntegerField()),
                ('question_number', models.IntegerField()),
                ('selected_answer', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'unique_together': {('student_id', 'class_id', 'test_num', 'question_number')},
            },
        ),
        migrations.CreateModel(
            name='StudentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.IntegerField()),
                ('class_id', models.CharField(max_length=255)),
                ('test_num', models.IntegerField()),
                ('student_id', models.CharField(max_length=50)),
                ('is_correct', models.BooleanField(default=False)),
                ('subject', models.CharField(max_length=50)),
                ('chapter', models.TextField()),
                ('topic', models.TextField()),
            ],
            options={
                'unique_together': {('question_number', 'class_id', 'test_num', 'student_id')},
            },
        ),
        migrations.CreateModel(
            name='SWOT',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=200)),
                ('class_id', models.CharField(max_length=200)),
                ('test_num', models.IntegerField()),
                ('swot_parameter', models.CharField(max_length=100)),
                ('swot_value', models.TextField()),
            ],
            options={
                'unique_together': {('user_id', 'class_id', 'test_num', 'swot_parameter')},
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('class_id', models.CharField(max_length=50)),
                ('test_num', models.IntegerField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'unique_together': {('id', 'class_id', 'test_num')},
            },
        ),
        migrations.CreateModel(
            name='TestProcessingStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_id', models.CharField(max_length=255)),
                ('test_num', models.IntegerField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('successful', 'Successful'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('logs', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(null=True)),
                ('ended_at', models.DateTimeField(null=True)),
            ],
            options={
                'unique_together': {('test_num', 'class_id')},
            },
        ),
    ]
