# Generated by Django 5.1.6 on 2025-11-17 09:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_educator_manager_overview_performance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestMetadata',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('class_id', models.CharField(max_length=50)),
                ('test_num', models.IntegerField()),
                ('pattern', models.CharField(choices=[('PHY_CHEM_BOT_ZOO', 'Physics → Chemistry → Botany → Zoology'), ('PHY_CHEM_BIO', 'Physics → Chemistry → Biology')], max_length=50)),
                ('subject_order', models.JSONField()),
                ('section_counts', models.JSONField(blank=True, null=True)),
                ('total_questions', models.IntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'exam_test_metadata',
                'unique_together': {('class_id', 'test_num')},
            },
        ),
    ]
