# Generated by Django 5.1.6 on 2025-12-04 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_result_bio_attended_result_bio_correct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='institution',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
