# Generated by Django 5.1.6 on 2025-12-05 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_manager_institution'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=200)),
                ('class_id', models.CharField(max_length=200)),
                ('feedback_value', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'exam_feedback',
                'ordering': ['-created_at'],
            },
        ),
    ]
