# Generated by Django 5.1.6 on 2025-12-06 06:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0007_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetRequest',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('role', models.CharField(choices=[('educator', 'Educator'), ('manager', 'Manager')], max_length=32)),
                ('token_hash', models.CharField(db_index=True, max_length=128)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('used', models.BooleanField(default=False)),
            ],
            options={
                'indexes': [models.Index(fields=['email', 'role'], name='exam_passwo_email_b962f0_idx'), models.Index(fields=['token_hash'], name='exam_passwo_token_h_15fc72_idx')],
            },
        ),
    ]
