# Generated by Django 5.1.6 on 2025-12-11 07:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0008_passwordresetrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='educator',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_id', models.CharField(max_length=255)),
                ('test_num', models.IntegerField()),
                ('notification_type', models.CharField(choices=[('TEST_COMPLETE', 'Test Processing Complete'), ('TEST_FAILED', 'Test Processing Failed')], default='TEST_COMPLETE', max_length=50)),
                ('sent', models.BooleanField(default=False)),
                ('attempts', models.IntegerField(default=0)),
                ('phone_number', models.CharField(max_length=20)),
                ('payload', models.JSONField(blank=True, null=True)),
                ('response_code', models.IntegerField(blank=True, null=True)),
                ('response_body', models.TextField(blank=True, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('educator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exam.educator')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['class_id', 'test_num'], name='exam_notifi_class_i_2f8ce8_idx'), models.Index(fields=['educator'], name='exam_notifi_educato_f3e1c7_idx'), models.Index(fields=['sent'], name='exam_notifi_sent_ea96fd_idx')],
                'unique_together': {('class_id', 'test_num', 'notification_type')},
            },
        ),
    ]
