# Generated by Django 5.1.6 on 2025-12-12 08:10

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0009_educator_phone_number_notificationlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('class_id', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=200)),
                ('teacher_name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('test_range', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, help_text='List of test numbers this teacher handled (e.g., [5, 6, 7])', null=True, size=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'teacher',
            },
        ),
    ]
