# Generated by Django 5.1.6 on 2025-12-28 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0010_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentresult',
            name='was_attempted',
            field=models.BooleanField(default=True),
        ),
    ]
