# Generated by Django 5.1.6 on 2025-12-28 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0011_studentresult_was_attempted'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmetadata',
            name='test_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
