# Generated by Django 5.1.6 on 2026-01-04 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0013_institution'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
