# Generated by Django 5.1.6 on 2026-01-06 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0014_manager_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='educator',
            name='whatsapp_activated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='educator',
            name='whatsapp_consent_ip',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='educator',
            name='whatsapp_consent_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='educator',
            name='whatsapp_first_interaction_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='educator',
            name='whatsapp_opt_in',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='educator',
            name='whatsapp_opt_in_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='manager',
            name='whatsapp_activated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='manager',
            name='whatsapp_consent_ip',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='manager',
            name='whatsapp_consent_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='manager',
            name='whatsapp_first_interaction_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='manager',
            name='whatsapp_opt_in',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='manager',
            name='whatsapp_opt_in_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
