# Generated by Django 5.1.6 on 2026-01-07 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0015_educator_whatsapp_activated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentresult',
            name='misconception',
            field=models.TextField(blank=True, null=True),
        ),
    ]
