# Generated by Django 5.1.6 on 2026-01-08 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0016_studentresult_misconception'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkpoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_id', models.CharField(max_length=255)),
                ('student_id', models.CharField(max_length=50)),
                ('test_num', models.IntegerField()),
                ('insights', models.JSONField(help_text='JSON array of checkpoint objects, each with checklist and action_plan fields')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'exam_checkpoints',
                'indexes': [models.Index(fields=['student_id', 'class_id'], name='exam_checkp_student_66e06a_idx'), models.Index(fields=['test_num'], name='exam_checkp_test_nu_d41bf2_idx')],
                'unique_together': {('class_id', 'student_id', 'test_num')},
            },
        ),
    ]
