# Generated by Django 5.1.6 on 2026-01-10 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0017_checkpoints'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='redirect_on_login',
            field=models.BooleanField(default=True),
        ),
    ]
