# Generated by Django 5.1.6 on 2026-01-14 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0018_institution_redirect_on_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentReport',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('class_id', models.CharField(db_index=True, max_length=100)),
                ('test_num', models.IntegerField(db_index=True)),
                ('student_id', models.CharField(db_index=True, max_length=50)),
                ('mark', models.FloatField(help_text="Student's score in this test")),
                ('average', models.FloatField(help_text="Student's average score across all tests")),
                ('improvement_rate', models.FloatField(help_text='Improvement rate compared to previous tests')),
                ('subject_wise', models.JSONField(default=dict, help_text='Subject-wise correct/incorrect/skipped counts. Format: {subject: {correct: n, incorrect: n, skipped: n}}')),
                ('subject_wise_avg', models.JSONField(default=dict, help_text='Subject-wise average scores across all students in the class. Format: {subject: avg_score}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-test_num', 'student_id'],
                'indexes': [models.Index(fields=['class_id', 'test_num'], name='exam_studen_class_i_70d3af_idx'), models.Index(fields=['student_id', 'class_id'], name='exam_studen_student_7a6c02_idx')],
                'unique_together': {('class_id', 'test_num', 'student_id')},
            },
        ),
    ]
