# Generated by Django 5.1.6 on 2026-01-14 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0019_studentreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentreport',
            name='subtopic_list',
            field=models.JSONField(default=dict, help_text='Top 6 subtopics per subject ranked by importance, with citations. Format: {subject: [{subtopic, rank, citations: [{test_num, question_num}]}]}'),
        ),
    ]
