# Generated by Django 5.1.6 on 2026-01-17 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0020_studentreport_subtopic_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentreport',
            name='class_vs_student',
            field=models.JSONField(default=list, help_text='Questions where class performed well but student failed. Format: [{question_num, correct_count, correct_option, student_option}]'),
        ),
        migrations.AddField(
            model_name='studentreport',
            name='sub_wise_marks',
            field=models.JSONField(default=dict, help_text='Cumulative marks per subject up to this test. Format: {subject: cumulative_marks}'),
        ),
    ]
