# Generated by Django 5.1.6 on 2026-01-31 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0021_studentreport_class_vs_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='domain',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
